#
#Mon Mar 23 03:42:55 ECT 2026
base.url=https\://www.saucedemo.com/
driver=chrome
chrome.driver=C\:\\Users\\carlos.reinado\\Downloads\\chromedriver-win64 (1)\\chromedriver-win64\\chromedriver.exe
capabilities.browserName=chrome
browserName=chrome
